# Site settings
title: Grant Marshall
email: gam@grantamarshall.com
description: "My (Grant Marshall) website and blog: where I write about programming, machine learning, computer science, and mathematics."
baseurl: ""
url: "http://grantamarshall.com"
github_username: gr-a-m
twitter_username: gr_a_m

# Build settings
markdown: kramdown
permalink: pretty

# Global settings
timezone: America/Phoenix
