# Site settings
title: Grant Marshall
email: gam@grantamarshall.com
description: "My (Grant Marshall) website and blog: where you can find what ML and programming projects I'm working on and other mathematics and music related posts."
baseurl: ""
url: "http://grantamarshall.com"
github_username: gr-a-m
twitter_username: gr_a_m

# Build settings
markdown: kramdown
permalink: pretty

# Global settings
timezone: America/Phoenix
